### ISSUE TITLE
I can't get it to install.

### ISSUE THREAD

**Issue by pastorryanhayden** [SitesForChurch/oc-churchgallery#6]
I have added it to www.blessedhopemtvernon.org and I've changed the path to churchgallery.  I'm seeing the components, but it's not adding a folder.  Do I need to add a ministry first?

**Comment by Codenator81** [comment]
I will test without ministry but should work alone. He shold create church_gallery folder

**Comment by Codenator81** [comment]
You change path there? https://github.com/SitesForChurch/oc-churchgallery/blob/master/config/config.php

**Comment by Codenator81** [comment]
plugin folder structure must be `sitesforchurch/churchgallery`
